version: '3'
services:
  traefik:
    image: 'traefik:3.0'
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - traefik-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./certs:/certs
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  proxy-dashboard:
    image: nginx:stable-alpine
    networks:
      - traefik-proxy
    volumes:
      - ./config/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
    labels:
      traefik.enable: true
      traefik.http.routers.proxy-dashboard.rule: Host(`traefik-dashboard.rundemoapp.com`)
      traefik.http.routers.proxy-dashboard.entrypoints: websecure
      traefik.http.routers.proxy-dashboard.tls: true
      traefik.http.services.proxy-dashboard.loadbalancer.server.port: 80

networks:
  traefik-proxy:
    external: true
